config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/', as: 'rails_admin'
  resources :cadastros
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cadastro.rb
class Cadastro < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cadastros_controller.rb
class CadastrosController < ApplicationController
  before_action :set_cadastro, only: [:show, :edit, :update, :destroy]

  # GET /cadastros
  # GET /cadastros.json
  def index
    @cadastros = Cadastro.all
  end

  # GET /cadastros/1
  # GET /cadastros/1.json
  def show
  end

  # GET /cadastros/new
  def new
    @cadastro = Cadastro.new
  end

  # GET /cadastros/1/edit
  def edit
  end

  # POST /cadastros
  # POST /cadastros.json
  def create
    @cadastro = Cadastro.new(cadastro_params)

    respond_to do |format|
      if @cadastro.save
        format.html { redirect_to @cadastro, notice: 'Cadastro was successfully created.' }
        format.json { render :show, status: :created, location: @cadastro }
      else
        format.html { render :new }
        format.json { render json: @cadastro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cadastros/1
  # PATCH/PUT /cadastros/1.json
  def update
    respond_to do |format|
      if @cadastro.update(cadastro_params)
        format.html { redirect_to @cadastro, notice: 'Cadastro was successfully updated.' }
        format.json { render :show, status: :ok, location: @cadastro }
      else
        format.html { render :edit }
        format.json { render json: @cadastro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cadastros/1
  # DELETE /cadastros/1.json
  def destroy
    @cadastro.destroy
    respond_to do |format|
      format.html { redirect_to cadastros_url, notice: 'Cadastro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cadastro
      @cadastro = Cadastro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cadastro_params
      params.require(:cadastro).permit(:brand, :model, :board, :color, :rental_value, :note)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cadastros_helper.rb
module CadastrosHelper
end

app/views/cadastros/_form.html.erb
<%= form_with(model: cadastro, local: true) do |form| %>
  <% if cadastro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cadastro.errors.count, "error") %> prohibited this cadastro from being saved:</h2>

      <ul>
      <% cadastro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model %>
  </div>

  <div class="field">
    <%= form.label :board %>
    <%= form.text_field :board %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color %>
  </div>

  <div class="field">
    <%= form.label :rental_value %>
    <%= form.text_field :rental_value %>
  </div>

  <div class="field">
    <%= form.label :note %>
    <%= form.text_field :note %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cadastros/edit.html.erb
<h1>Editing Cadastro</h1>

<%= render 'form', cadastro: @cadastro %>

<%= link_to 'Show', @cadastro %> |
<%= link_to 'Back', cadastros_path %>

app/views/cadastros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cadastros</h1>

<table>
  <thead>
    <tr>
      <th>Brand</th>
      <th>Model</th>
      <th>Board</th>
      <th>Color</th>
      <th>Rental value</th>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cadastros.each do |cadastro| %>
      <tr>
        <td><%= cadastro.brand %></td>
        <td><%= cadastro.model %></td>
        <td><%= cadastro.board %></td>
        <td><%= cadastro.color %></td>
        <td><%= cadastro.rental_value %></td>
        <td><%= cadastro.note %></td>
        <td><%= link_to 'Show', cadastro %></td>
        <td><%= link_to 'Edit', edit_cadastro_path(cadastro) %></td>
        <td><%= link_to 'Destroy', cadastro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cadastro', new_cadastro_path %>

app/views/cadastros/new.html.erb
<h1>New Cadastro</h1>

<%= render 'form', cadastro: @cadastro %>

<%= link_to 'Back', cadastros_path %>

app/views/cadastros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Brand:</strong>
  <%= @cadastro.brand %>
</p>

<p>
  <strong>Model:</strong>
  <%= @cadastro.model %>
</p>

<p>
  <strong>Board:</strong>
  <%= @cadastro.board %>
</p>

<p>
  <strong>Color:</strong>
  <%= @cadastro.color %>
</p>

<p>
  <strong>Rental value:</strong>
  <%= @cadastro.rental_value %>
</p>

<p>
  <strong>Note:</strong>
  <%= @cadastro.note %>
</p>

<%= link_to 'Edit', edit_cadastro_path(@cadastro) %> |
<%= link_to 'Back', cadastros_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAdmin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>